### ISSUE TITLE
The name FastClick seems to trigger antivirus/anti-spyware software

### ISSUE THREAD

**Issue by bensaufley** [ftlabs/fastclick#108]
It looks like, based on some Googling, "FastClick.net" is a spyware/virus indicator. I've been developing on a Mac with no problems but when we started testing on a PC, RequireJS dependencies with FastClick were failing - in Chrome, the response headers seemed to indicate the browser was being served image/gif instead of application/javascript. I was baffled until I noticed that the "Server" was KAV/7.0 instead of IIS. Kaspersky, the antivirus software, appears to have been intercepting and mangling the file so that the PCs running Kaspersky were unable to load fastclick.js. I believe I've confirmed the name is the issue because I renamed the file quickclick.js and all of its instances QuickClick and the problem has vanished.

**Comment by romaincointepas** [comment]
One of my website users has encountered the problem with an up-to-date Kapersky database (Feb 1, 2015).

If needed, I can easily spawn a VM and reproduce myself.

Here is a screenshot:

**Comment by lex-js** [comment]
Latest KAV database, same issue as on @romaincointepas's screenshot.
The problem still exists.
