### ISSUE TITLE
Use FastClick only for items matching selector

### ISSUE THREAD

**Issue by marcovtwout** [ftlabs/fastclick#109]
I know it's possible with 'needsclick' to make exceptions for fastclicking within the selected layer.

Instead, I'd like to attach fastclick only to selected elements (for example, having class="fastclick"). Is this possible?

**Comment by bathindavarinder** [comment]
FastClick don't even work with 'textarea' element. It doesn't open keyboard when you click on it, i found a work around for it. Let me know if anybody needs help in that.
