### ISSUE TITLE
Add .needsclick support to all child elements

### ISSUE THREAD

**Issue by peterostrander** [ftlabs/fastclick#119]
Hi there,

I'm using the Google Maps API to embed a map on a site, but fastclick disables the ability to tap any of the buttons inside the embed that control Street View, satellite view, etc (I assume Google has their own implementation that's interfering). Of course this only effects touch devices.

It would be nice to have an added class, maybe .needclick-children, that allows for a non-synthetic click on all child elements of a div.

Thanks.

**Comment by MiguelMadero** [comment]
@rstacruz @matthew-andrews  thanks the `on('touchstart')` did the trick.
