### ISSUE TITLE
iOS5 'emulated' touch events not working

### ISSUE THREAD

**Issue by steffanwilliams** [ftlabs/fastclick#120]
Hello there,

This library isn't firing click events with Chrome (on desktop) having 'Emulate touch events' enabled, and set to a User Agent string of:
**Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3**

This is visible on: http://app.ft.com/

If you use a User Agent string of iOS4:
**Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5**

It works perfectly fine.

It looks like the issue is in **FastClick.prototype.onTouchStart**, more specifically the 'return false;' is being fired as both touch identifiers are set to 0.

``` javascript
if (!this.deviceIsIOS4) {

  // Weird things happen on iOS when an alert or confirm dialog is opened from a click event callback (issue #23):
  // when the user next taps anywhere else on the page, new touchstart and touchend events are dispatched
  // with the same identifier as the touch event that previously triggered the click that triggered the alert.
  // Sadly, there is an issue on iOS 4 that causes some normal touch events to have the same identifier as an
  // immediately preceeding touch event (issue #52), so this fix is unavailable on that platform.
  if (touch.identifier === this.lastTouchIdentifier) {
    event.preventDefault();
    return false;
  }
  ...
}
```

Would this just be an issue with the emulator, or is this possible that actual phones with the IOS5 User Agent would have the same problem? (I don't have one to hand in order to test)

**Comment by hackhat** [comment]
Still an issue with the current npm version... But not all "taps" are affected, only some of them... Works on the real device.
