### ISSUE TITLE
iOS: Selects don't work with Voiceover

### ISSUE THREAD

**Issue by betabong** [ftlabs/fastclick#226]
This is IMHO quite a critical bug considering the amount of websites using this library:

With Fastclick activated, people using VoiceOver on iOS are not able to open a select box (popover) anymore.

Example: http://cdpn.io/blGmH
Pen: http://codepen.io/betabong/pen/blGmH/

There are scenarios though that work:
- When using the form navigation (above the keyboard < and >)
- When another form element has focus (keyboard is open) and then selecting the popover button

**Comment by ewout1** [comment]
I can confirm that this voiceover fix in fastclick still causes the select fields to be buggy. We almost removed fastclick for it until we found this threat.
