### ISSUE TITLE
Unbinding fastclick

### ISSUE THREAD

**Issue by rstacruz** [ftlabs/fastclick#234]
Is the an easy way to temporarily unbind fastclick?

I'd love to be able to do this for a few scenarios:
- Google's places autocomplete doesn't play well with Fastclick, and `needsclick` isn't a solution that works. I'd like to temporarily disable Fastclick altogether while a Google autocomplete widget is around.
- I may be using Rails's Turbolinks, and would like fastclick to run only on certain pages. This means it'd have to be unbound once these pages are navigated away from.

**Comment by aghouseh** [comment]
The destroy method is part of the FastClick prototype, so you'll need to save a reference to the FastClick instance and call destroy() on that object.

```javascript
var fastclick = FastClick.attach(document.body);
...
fastclick.destroy();
```

I was able to resolve the google maps autocomplete conflict perfectly by using this method.
