### ISSUE TITLE
label onclick event doesn't work on iOS 7

### ISSUE THREAD

**Issue by BYODKM** [ftlabs/fastclick#275]
When label has `for` attribute, onclick event doesn't fire.
Without `for`, works fine. But checkbox doesn't get checked.

	<input id="checkbox" type="checkbox">
	<label for="checkbox" onclick="console.log('Hi')">label</label>
	<script>FastClick.attach(document.body);</script>

FastClick.js version 1.0.2.

**Comment by Fortuitous** [comment]
@BYODKM 
You marked this closed, but the thread does not make clear what is best / recommended solution, thanks.

**Comment by Ruff9** [comment]
None of the solutions here is working for me. Doesn't look like a closed issue.

**Comment by genyklemberg** [comment]
Check for other use of label attribute in JS or CSS. Even changed width of label can cause problems

**Comment by BYODKM** [comment]
@genyklemberg Thanks!

**Comment by OscarGodson** [comment]
@BYODKM why did you close this? Was this fixed?

**Comment by BYODKM** [comment]
@OscarGodson Nothing. But you can't fix this. This is a ground rule of JavaScript as @genyklemberg mentioned.

**Comment by OscarGodson** [comment]
I don't think that's what he pointed out, or if it is, It's not a ground rule of JS. If you remove fastclick and write one-off code I can get this to work pretty easily since that's default browser behavior on touch devices. I just don't know how to integrate into FastClick's code base.

**Comment by BYODKM** [comment]
@OscarGodson I think this is because of FastClick's nature, `label onclick` is a collision course. Sorry, but I have to say "Just don't".

**Comment by mqliutie** [comment]
So, what is the best solution?

**Comment by tjcafferkey** [comment]
I wrote about the same issue I had here: http://www.tjcafferkey.me/problems-clicking-input-label-select-ios-safari/

The fix I put in was simply

`label > * {
pointer-events:none;
}`

**Comment by ricardozea** [comment]
FWIW, there's still an issue in which for example if the `<label>` has a styling on `:hover` it will remain styled after the user taps again to uncheck a checkbox:

![file jun 20 10 36 17 am](https://user-images.githubusercontent.com/1656481/27338905-5d5336b8-55a4-11e7-98c9-33149fbea90f.jpeg)

So the only solution is to have no styling on the `<label>` on  small screen device and then add it at a certain breakpoint for large screens.

Bummer 😞
