### ISSUE TITLE
Breaks 'Open Link in New Tab' functionality in some browsers

### ISSUE THREAD

**Issue by ironsidevsquincy** [ftlabs/fastclick#292]
### To replicate

 * Use FastClick
 * Hold down touch on a link, so 'Open Link in New Tab'  menu opens, and select it

### Result

 * In FireFox, Android 2.2.3 - New page loads in current tab; no need tab is opened
 * In default browser, Android 4.1.1 - Page opens in new tab correctly, but going back to original tab causes page to load in

### Expected

 * Current tab maintains page, selected link opens in new tab

e.g. http://jsfiddle.net/yr3rdwkv/10/embedded/result/

**Comment by matthew-andrews** [comment]
I believe this should be fixed now
