### ISSUE TITLE
FastClick not working for input inside label

### ISSUE THREAD

**Issue by adrianosmond** [ftlabs/fastclick#30]
The w3c spec for label: http://www.w3schools.com/tags/tag_label.asp says (in the tips and notes section): "A label can be bound to an element either by using the "for" attribute, or by placing the element inside the <label> element."

While FastClick works well for the first case, it doesn't work for the second. Visit http://jsfiddle.net/adrianosmond/7tq2d/5/embedded/result/ on a touch screen device for an example

**Comment by anjianshi** [comment]
I find a new problem, if I click a `<span>` in `<label>`， the `<input>` inside this label won't foucs.

```html
<label>
    <span>title</span>
    <input type="checkbox" />
</label>
````

**Comment by anjianshi** [comment]
I find a new problem, if I click a `<span>` in `<label>`， the `<input>` inside this label won't foucs.

```html
<label>
    <span>title</span>
    <input type="checkbox" />
</label>
```
