### ISSUE TITLE
Windows Phone 8.1: select and input elements not usable

### ISSUE THREAD

**Issue by michaelboellet** [ftlabs/fastclick#304]
Fastclick works great with Windows Phone 8.0 but since the 8.1 upgrade I have a strange behavior on select and input elements. On selects I can't choose an option, the options are not even showing up. I can click on input elements but the keyboard is not showing, only until I click multiple times on the field.

I've tested it with my Lumia 920 on two projects which use Fastclick, both have the same behavior. Is this a known bug? Couldn't find any info about this yet. Thanks!

**Comment by alexdiliberto** [comment]
Also confirming this is an issue with v1.0.3 and WinPhone 8.1

Spent a couple hours debugging today only to find it was FastClick... :confused:

**Comment by matthew-andrews** [comment]
I'm sorry you had to spend so many hours debugging FastClick.  As long as you set up the correct CSS classes, FastClick shouldn't even do anything on IE10+ but it looks like our check for this didn't match the advice we were giving in our `README.md`.

Would you mind trying this version? https://github.com/ftlabs/fastclick/blob/match-ie10%2B-advice/lib/fastclick.js

**Comment by davidhouweling** [comment]
Hi Matthew, I've tried the suggested version in Windows Phone 8.1 Update 1 Emulator and on a Nokia Lumia 920 (with developer preview) and it appears to work.

**Comment by matthew-andrews** [comment]
Unfortunately I don't have a device to test this on, but going to go by @davidhouweling's verification in this case and say that this is fixed in v1.0.5.
