### ISSUE TITLE
ie11 Object doesn't support this action

### ISSUE THREAD

**Issue by Mellivora** [ftlabs/fastclick#348]
Hello,

I am using jquery and a pre minified version of fastclick (1.0.3).

On ie11 I get the error: Object doesn't support this action and in the developer tools this line of code is highlighted:
{document.dispatchEvent(new CustomEvent('o.DOMContentLoaded'))}

Cheers.

**Comment by matthew-andrews** [comment]
Ah a custom event polyfill is needed to use the build service.  May I suggest you use our Polyfill Service (https://cdn.polyfill.io/v1/docs/) or using the [raw FastClick JavaScript](https://github.com/ftlabs/fastclick/blob/master/lib/fastclick.js) & minifying yourself?

**Comment by Mellivora** [comment]
Brilliant, thank you very much Matthew, I will have a look at that.
