### ISSUE TITLE
Fasclick not needed with Firefox >= 30

### ISSUE THREAD

**Issue by mk747gx** [ftlabs/fastclick#355]
Firefox for Android removed the 300 ms click delay in version 30. (https://bugzilla.mozilla.org/show_bug.cgi?id=941995)

I tested the delay with http://ftlabs.github.io/fastclick/examples/layer.html. With Firefox for Android versions 30 and up the remaining delay is negligible (5-10 ms). 

So maybe FastClick should be disabled for these browser versions.

PS: I had some bugs when using FastClick with Firefox 34 so a fix might be neccessary. If you do not want to add Firefox to the ignore list, I will open a new issue with the bugs I had

**Comment by matthew-andrews** [comment]
Yes, you're right… Firefox should be disabled for Firefox versions 30+.

https://developer.mozilla.org/en-US/Firefox/Releases/30/Site_Compatibility

**Comment by matthew-andrews** [comment]
Released in `v1.0.6`
