### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Flash-back** [ftlabs/fastclick#362]
Does fastclick works with Firefox?

Greetings.

**Comment by Flash-back** [comment]
I mean the mobile version.

**Comment by matthew-andrews** [comment]
It should.  Is it not working how you expect on Firefox mobile?

**Comment by matthew-andrews** [comment]
Firefox Mobile does it natively as long as you provide appropriate meta tags.

> Both Firefox for Android and Firefox OS support double-tap-to-zoom, and there is a 300-millisecond delay between the touch event (touchend) and the mouse event (click) to detect and enable this gesture. In order to improve the responsiveness of applications, this delay has been removed on non-zoomable, responsive designed pages that specify width=device-width (or some value less than device-width) and/or user-scalable=no in the viewport <meta> tag. Google Chrome 32 also removed the delay. Read an article on HTML5 Rocks for details.

https://developer.mozilla.org/en-US/Firefox/Releases/30/Site_Compatibility
