### ISSUE TITLE
FastClick on iOS 8 appears to auto close select elements when tapped

### ISSUE THREAD

**Issue by tombell** [ftlabs/fastclick#369]
I've debugged this down to a fastclick.js issue as when I disable fastclick.js the issue goes away.

Here is a screencast of the issue encountered: http://cl.ly/1d212h32271j

After some more testing it appears a "faster" tap causes the issue, and a "slower" tap doesn't.

**Comment by SergeySolonko** [comment]
I've got the same issue. 

+ to resolve it

**Comment by SergeySolonko** [comment]
Try to add additional class to select and see if it works for you.

```
<select name="reason" class="needsclick needsfocus">
....
</select>
```

**Comment by ewendel** [comment]
I'm also experiencing this problem. I (temporarily) fixed it by modifying the source to disabe fastclick for <select>-elements:

```
if (targetElement.nodeName.toLowerCase() == "select") {
    return false;
}
```

On line 396 in Fastlick.prototype.onTouchStart

**Comment by longhornleads** [comment]
This was a definite issue for my app as well and this provided a great temp fix!  Any word on an update?
