### ISSUE TITLE
Issue with iframe on iOS

### ISSUE THREAD

**Issue by rajushank84** [ftlabs/fastclick#37]
When used on a page loaded in an iframe, on iOS devices (specifically iPad), inputs dont work. I mean, if the page inside an iframe has an &lt;input type=text&gt;, on iPad when you focus the field the touch keyboard shows up but you cant type.

**Comment by bigotedWhale** [comment]
it's not about the broswer , it's about the specific version of the browser kernel，to solve this problem, just use :`docment.addEventListener('touchend', () => { window.focus()})`
https://stackoverflow.com/questions/13124340/cant-type-into-html-input-fields-on-ios-after-clicking-twice
