### ISSUE TITLE
AMD, sure? Is it not CommonJS instead?

### ISSUE THREAD

**Issue by kud** [ftlabs/fastclick#370]
https://github.com/ftlabs/fastclick#amd

- AMD

```
define(['jquery'] , function ($) {
    return function () {};
});
```
- CommonJS

```
var $ = require('jquery');
exports.myExample = function () {};
```

**Comment by cmwelsh** [comment]
They are showing RequireJS ["sugar"](http://requirejs.org/docs/whyamd.html#sugar) style:

    define(function (require) {
        var $ = require('jquery');

        $('.foo').bar();
    });

**Comment by kud** [comment]
ooooooooooooh okay, thank you.
