### ISSUE TITLE
fastclick and slider

### ISSUE THREAD

**Issue by quape** [ftlabs/fastclick#378]
Hi there,

I'm using fastclick together with jquery ui slider. fastclick works fine on all elements except the slider. Simply nothing happens when trying to drag the handle.

When I disable fastclick for that element (by adding needsclick class) then the handle moves to certain areas by clicking on them (and of course after the 300 ms delay). Dragging is still not possible.

It's maybe not a directly problem of fastclick but does anyone know how to solve that? I just want a simple slider with a draggable handle.

Greetings
Mat

**Comment by quape** [comment]
Solved: I dropped jQuery UI slider and switched to leightweight noUISlider. With that, fastclick works perfect and without "needsclick".

**Comment by iamstarkov** [comment]
@quape then close your issue
