### ISSUE TITLE
fasclick and swipe elements

### ISSUE THREAD

**Issue by dkot** [ftlabs/fastclick#389]
Hi,
I'm working for digital advertising company and our partners using fasclick on their web site. And we faced an issue that because of fastclick swipe and other rich media creatives are not working - click triggered instead of swipe. needsclick is also on working as expected. Is it possible at all to skip some elements from fastclick handling, or the only way is to detach fasclick from body and attach to everything, but some elements
Example:  http://euroman.dev.workingpropeople.com/

**Comment by iamstarkov** [comment]
I’m not sure, but for me "to detach fasclick from body and attach to everything, but some elements" is the only way

**Comment by dkot** [comment]
Yes that obvious solution, but requires more work to be done. Anyways thank you for reply.

**Comment by matthew-andrews** [comment]
@dkot might [selective fastclick](https://github.com/matthew-andrews/selective-fastclick) help you?
