### ISSUE TITLE
proposal for reactjs

### ISSUE THREAD

**Issue by iamstarkov** [ftlabs/fastclick#394]
Can you write instruction how to integrate fastclick with reactjs?

**Comment by cmwelsh** [comment]
Here's how I integrate them:

    var FastClick = require('fastclick');
    FastClick.attach(document.body);

**Comment by iamstarkov** [comment]
and does it work well with synthetic events in reactjs?

**Comment by cmwelsh** [comment]
It seems to be fully functional with typical React.js code:

    <div onClick={ this.handleClick } />

**Comment by iamstarkov** [comment]
I’m 80% sure this will not work. Have you seen first SO answer on this problem?

**Comment by iamstarkov** [comment]
Have you tried?

**Comment by cmwelsh** [comment]
I use the above code on my application. I'm considering switching to [selective-fastclick](https://github.com/matthew-andrews/selective-fastclick) due to various issues on iOS.

**Comment by iamstarkov** [comment]
Okay, maybe I don't understand something. Why you can use it simple `onClick` and this guy from SO [have to write 80 line component][so] to force fastclick work properly with reactjs?

[so]: http://stackoverflow.com/a/24345469/1057730

**Comment by cmwelsh** [comment]
I don't know. https://github.com/facebook/react/issues/2753 is a corresponding issue on the React project.

**Comment by iamstarkov** [comment]
In Issue you linked people are talking about the same as I: fastclick is not working with react from a box

**Comment by iamstarkov** [comment]
For anybody lurked for reactjs implementation, take a look at https://www.npmjs.com/package/react-tap-event-plugin
