### ISSUE TITLE
user-scalable="no" still has delay on ios8

### ISSUE THREAD

**Issue by iamgoodbytes** [ftlabs/fastclick#409]
I understand that fastclick doesn't need to be activated when using user-scalable="no", as browsers should handle this since there is no zoom action. However, I'm still noticing the delay on ios8 when I have user-scalable set to "no". Is that normal behaviour or am I missing something?

I'd like to remove the delay so that my app feels faster, while still maintaining user-scalable="no"

**Comment by vincentorback** [comment]
That’s because Safari hasn’t implemented this feature yet. It’s really just working in Chrome on Android for now. So what I would do is use Fastclick for faster touching on iOS and `user-scalable="no"` if you want to disable zooming.

**Comment by iamgoodbytes** [comment]
Hi @vincentorback - I guess what I'm trying to say is that I'm still getting a 300ms delay, even when using fastclick, on iOS. The delay happens in both safari and chrome on ios, so I'm wondering if there's anything else I might be missing?

**Comment by vincentorback** [comment]
Do you notice the delay without `user-scalable="no"`? If so then it’s probably doesn’t have much to do with that and more with that Fastclick isn’t activated at all? Not sure how to test for that though.

**Comment by iamgoodbytes** [comment]
Yes, user-scalable isn't blocked and I'm still having the delay. It's weird because I see that FastClick is attached via `FastClick.attach(document.body);`

I'm using the adminlte template where fastclick is implemented. Could you give it a quick go at https://almsaeedstudio.com/themes/AdminLTE/index2.html on your iphone? You can notice the delay when opening the hamburger menu on the top left and opening subnav's.

I hope I'm not imagining delays :)

**Comment by vincentorback** [comment]
Yeah I get the delay as well. Perhaps Fastclick is initializwd before the content is loaded?

**Comment by iamgoodbytes** [comment]
The script gets loaded at the very bottom of my page so I doubt that. I'll try to look into it further and see if anyone over at adminLTE knows more about the issue. Thanks for looking into it!

**Comment by iamgoodbytes** [comment]
This was a problem with adminLTE, not with FastClick!
