### ISSUE TITLE
FastClick.js Does Not Eliminate the Touch Event Delay on Safari iOS 9.2 

### ISSUE THREAD

**Issue by pepitz** [ftlabs/fastclick#458]
Hi,

I've recently implemented FastClick.js library on my website (www.petartsenev.com) but still have the **iOS Safari browser** delay on “touch” event triggered on my mobile menu <button>.

Could you please help me solve the problem. Attached are my files. 
I've tested the website on iPhone 4S with iOS 9.2.1.
Here's a link to the code in JSBIN [https://jsbin.com/vejavu/edit](url)

Thank You!

**Comment by pepitz** [comment]
[](url)

**Comment by makc** [comment]
self-resolved in 4 minutes... or just spamming your site link?

**Comment by pepitz** [comment]
Sorry, I can not understand you!
