### ISSUE TITLE
Fastclick.js being blocked by AdBlock

### ISSUE THREAD

**Issue by mrlilly** [ftlabs/fastclick#464]
Has anybody had any issues with the fastclick.js file being blocked by AdBlock in Chrome (49)?

**Comment by rowanbeentje** [comment]
:D fastclick used to be an advertising network (https://en.wikipedia.org/wiki/Fastclick - up until 2005 it seems!)

**Comment by HarryPhillips** [comment]
I have taken a look at the forums for EasyList, the large filter which AdBlock downloads regularly. They have since removed it from their filter, it was a mistake it seems. 

If you go to filter preferences and then down to EasyList and actions, you can click "update filters". Should be good to go!

**Comment by mrlilly** [comment]
Thank you very much for the quick responses. Updating the filters resolved the issues.
Thank you once again.
