### ISSUE TITLE
Issue with iframe inside cordova app on ios 9.3

### ISSUE THREAD

**Issue by nihilus** [ftlabs/fastclick#474]
Got an issue (which disappears if I don't use fastclick.js):
I'm having a Cordova app fetching a webpage inside the app in an iframe (yeah, I know it shouldn't be done this way) and then shows the page.

It is developed in Intel XDK and works good, however if I focus on an text-input-box I can hardly tap outside it to blur. Seems like the blur event goes unnoticed to /dev/null or something like it.

It all works fine in Mobile Safari.

Anyone has got a clue?

**Comment by Seitenwerk** [comment]
Take a look at this bug here, I have a feeling its the same problem: http://stackoverflow.com/a/31424239/1731388

**Comment by nihilus** [comment]
Doesn't look like it. Removed binding to fastclick and added an event listener to touchstart without the problem.

**Comment by nihilus** [comment]
This did it work!
`Index: ../COMMON/MOBILE/www/bower_components/fastclick/lib/fastclick.js
===================================================================
--- ../COMMON/MOBILE/www/bower_components/fastclick/lib/fastclick.js	(revision 16326)
+++ ../COMMON/MOBILE/www/bower_components/fastclick/lib/fastclick.js	(working copy)
@@ -273,6 +273,7 @@
 			case 'file':
 			case 'image':
 			case 'radio':
+			case 'text':
 			case 'submit':
 				return false;
 			}
@@ -306,6 +307,10 @@
 		clickEvent.initMouseEvent(this.determineEventType(targetElement), true, true, window, 1, touch.screenX, touch.screenY, touch.clientX, touch.clientY, false, false, false, false, 0, null);
 		clickEvent.forwardedTouchEvent = true;
 		targetElement.dispatchEvent(clickEvent);
+
+		event.stopPropagation();
+		event.preventDefault();
+		return false;
 	};
 
 	FastClick.prototype.determineEventType = function(targetElement) {
@@ -572,6 +577,7 @@
 			// Case 1: If the touch started a while ago (best guess is 100ms based on tests for issue #36) then focus will be triggered anyway. Return early and unset the target element reference so that the subsequent click will be allowed through.
 			// Case 2: Without this exception for input elements tapped when the document is contained in an iframe, then any inputted text won't be visible even though the value attribute is updated as the user types (issue #37).
 			if ((event.timeStamp - trackingClickStart) > 100 || (deviceIsIOS && window.top !== window && targetTagName === 'input')) {
+				this.focus(targetElement);
 				this.targetElement = null;
 				return false;
 			}
@@ -603,6 +609,8 @@
 		// real clicks or if it is in the whitelist in which case only non-programmatic clicks are permitted.
 		if (!this.needsClick(targetElement)) {
 			event.preventDefault();
+
+			this.focus(targetElement);
 			this.sendClick(targetElement, event);
 		}
 
`

**Comment by fbarletta** [comment]
Is this issue still going on? We're having the same issue and nothing has fixed it.

**Comment by nihilus** [comment]
Did you try my fix?

**Comment by fbarletta** [comment]
Yes. We also just disabled fastclick and it did not resolve it. Actively trying to figure out what could be causing this same issue.
