### ISSUE TITLE
Failed to execute setSelectionRange on input type 'email'

### ISSUE THREAD

**Issue by klzns** [ftlabs/fastclick#485]
Error happening on Chrome 51 
![setselectionrangeerror](https://cloud.githubusercontent.com/assets/284515/17310913/e290ea76-581d-11e6-925c-b2465076bf91.png)

**Comment by thmzlt** [comment]
I'm getting the same error for input type `number`.

**Comment by scokmen** [comment]
I'm getting the same error. Is there any workaround for this?

**Comment by ritox842** [comment]
Check out https://github.com/ftlabs/fastclick/issues/530
