### ISSUE TITLE
[BUG] Fastclick throws `passive event listener` error in Chrome >= 56

### ISSUE THREAD

**Issue by buscape** [ftlabs/fastclick#510]
Hey guys, thanks to this new Chrome Policy https://www.chromestatus.com/features/5093566007214080
fastclick will throw an Error on Chrome >= 56 .

Steps to reproduce:
1. Use a chrome browser in version 56 or higher (Canary, Chromium...)
2. Trigger the onTouchStart method of fastclick.
3. See the error message in the console.
![image](https://cloud.githubusercontent.com/assets/2746610/20567784/58799938-b19a-11e6-98fe-d6819bbb881f.png)

The piece of code causing the error is here:
https://github.com/ftlabs/fastclick/blob/3db9f899c25b7b2e1517dc5cc17494ec9094bc43/lib/fastclick.js#L421

**Comment by RByers** [comment]
Sorry for the trouble, there's some guidance [here](https://developers.google.com/web/updates/2017/01/scrolling-intervention).

But fastclick really shouldn't be kicking in on Chrome (or [any other modern browser](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)) - does your site not have a mobile viewport?  You can explicitly set `touch-action: manipulation` to eliminate the need for fastclick if you really can't use a mobile viewport.

**Comment by buscape** [comment]
Thanks for the tip! In our case fastclick was kicking in because we're forced to manipulate the user agent (terrible idea...).
