### ISSUE TITLE
Disable fastclick entirely, ONLY for a specific (dynamic) element

### ISSUE THREAD

**Issue by michahell** [ftlabs/fastclick#526]
Hello, 

We have a use-case where a dynamically generated element (Angular 1.6 component) 
stops working when we use FastClick. It uses SVG elements as a checkbox representation, which already is a bit of hack, but that aside, it works in all browsers. In our IOS project, however, it doesn't, because we use FastClick (attached to the body of our app). We know this, because completely removing FastClick makes the component work again.

We have used the `needsclick` class but that does not seem to work (we checked the source, and using `needsclick` does propagate the original event, **but FastClick still intercepts the original one**)

We have looked into only enabling FastClick on specific DOM elements, but that would mean a huge number of separate instantiations of FastClick, which next to a lot of work would probably not be very performant either (that's a guess).

My question is this: Is it possible to remove FastClick behaviour entirely from just one specific element?

**Comment by warmhug** [comment]
+1

**Comment by daykkin** [comment]
+1 for one block and all dynamic elements in this block.. very needed

**Comment by michahell** [comment]
We ended up using this fork: https://github.com/zenput/fastclick

**Comment by homerlex** [comment]
@michahell - what is the diff on that branch that makes it work for you?

**Comment by MikeSperone** [comment]
+1 - any solution to this, still using this library (and not a fork)?
