### ISSUE TITLE
Vue 引入fastclick后IOS的input聚焦延迟解决方案

### ISSUE THREAD

**Issue by liyaocool** [ftlabs/fastclick#583]
//main.js 引入
`import FastClick from 'fastclick';`
`FastClick.attach(document.body);`
`FastClick.prototype.focus = (ele) => {
  'use strict';
  ele.focus();
}; //修改focus()方法`

**Comment by RoseEnd** [comment]
老哥你这样能解决ios  input聚焦问题不

**Comment by liyaocool** [comment]
可以,已经解决.就这3行代码,不用其他

**Comment by liyaocool** [comment]
> 老哥你这样能解决ios input聚焦问题不

可以,就用这3行代码,不用其他

**Comment by RoseEnd** [comment]
嗯，在之前的issue里也找到了相似的解决方案

**Comment by GiteeTimo** [comment]
同延迟

**Comment by owen800q** [comment]
> 同延迟

解决了吗，我折腾了几天还没搞定。。。

**Comment by javanoclaw** [comment]
改源码 增加 ele.focus();，

**Comment by javanoclaw** [comment]
改源码 增加 ele.focus();，

**Comment by javanoclaw** [comment]
改源码 增加 ele.focus();，
