### ISSUE TITLE
Add Note: Fastclick since iOS 9.3 not longer neccessary when using WKWebView

### ISSUE THREAD

**Issue by GitToTheHub** [ftlabs/fastclick#591]
Hi,
since iOS 9.3, when using WKWebView, the 300-350ms delay is gone. In Android it's gone since Chrome Version 32+. Could you maybe add this hint on your readme? Thanks.

Related Issue here: https://github.com/ftlabs/fastclick/issues/514
Webkit-Bugfix: https://bugs.webkit.org/show_bug.cgi?id=153180 (see second last comment)

(In UIWebView the fix is not working!)

**Comment by bmitchinson** [comment]
This is now addressed in the readme and can be closed, thanks 👍

**Comment by GitToTheHub** [comment]
In which readme? I couldn't find it in the readme of this git-repo.

**Comment by GitToTheHub** [comment]
Ah ok, i think i saw this notice already before i opened this issue. Because it's not explicit when you are an app developer. If you develop for Apple it's important to know that you must develop with the WKWebView component instead of the UIWebView component to avoid this problem. But I don't care. I don't want to put too much energy in this here.

**Comment by GitToTheHub** [comment]
I was right, the comment is from 2016: https://github.com/ftlabs/fastclick/commit/4e409926198147f24a49c293923d2a2a047c3774
Thank's for adressing it NOW in the readme ..
