### ISSUE TITLE
Fastclick not selecting input for inline elements within a label element

### ISSUE THREAD

**Issue by nnnick** [ftlabs/fastclick#60]
If there is an inline element inside the label element - the targetElement.tagName isn't 'label', so the findControl function is never hit.

Perhaps check if the parent node is a label then call findControl on the parent node?

FYI using testing iOS 6.0.1

**Comment by kerryj89** [comment]
While the 'pointer-events: none' works for most users, it doesn't work well for those with "heavy" fingers, at least in my case.  After seeing older users use the touch interface, in my situation they tend to make heavier taps and it seems to register doubly (to the effect of checking and rapidly unchecking just as they lift their finger).  Their taps tend to be somewhere between a normal tap and a selection touch hold.  Removing fast-click makes it work 100% of the time in duration between a tap and a selection hold.  Do you think this is a limitation of fast-click, or am I doing something wrong?

HTML:
`<label><input type="checkbox"><span></span></label>`

CSS:
```
label > * { pointer-events: none; }

input[type=checkbox] {
	display: none;
}
input[type=checkbox] + span {
	display: inline-block;
	position:relative;
	background: #fff;
	border: 1px solid #C8C8C8;
	height: 24px;
	width: 24px;
	padding: 0;
	vertical-align:top;
	margin-left:0.25rem;
	-webkit-transition: background .1s;
	transition: background .1s;
}
input[type=checkbox]:checked + span {
	border: 2px solid #fff;
	outline: 1px solid #C8C8C8;
	background: #2f86c4;
}
```

**Comment by marksy** [comment]
@mattcg thanks man, "label > * { pointer-events: none; }" also fixed it for me. Feulf!

**Comment by whosesmile** [comment]
@mattcg ,thanks~

**Comment by ravikiran438** [comment]
If cursor needs to be added try like below:
label { cursor:pointer; } label > * {pointer-events:none;}

**Comment by jackyon** [comment]
label > * { pointer-events: none; }

this works for me. thx!

**Comment by tomplays** [comment]
thanks guys ! hours spent to find this fix  (label > * { pointer-events: none; })

**Comment by mzaslavsky** [comment]
I suppose it should be pointed out that

    label > * { pointer-events: none; }

will affect everything within the label and one may need some specific exceptions in addition to some general ones, such as links within labels:

    label a { pointer-events: all; }

I haven't fully tested anything though.

**Comment by vinithjsamuel** [comment]
/*Jquery Fix*/
$('input').on('click',function(){
        $(this).focus();
});
This worked in my case. Thanks

**Comment by cl984430825** [comment]
so good,this is good methods
