### ISSUE TITLE
Tapping triggers hover event on other elements

### ISSUE THREAD

**Issue by peterostrander** [ftlabs/fastclick#83]
I'm seeing an issue where tapping on the screen can sometimes trigger the css :hover state of an element outside of that tap. I've uploaded a video of what I'm seeing in the iPhone Simulator. I'm getting the same bug on my iPhone 5.

http://www.screencast.com/t/poflecU6OX

**Comment by nspo** [comment]
Had the same problem on an iPad 1 (iOS 5) with Bootstrap 3 and buttons as checkboxes.
The following CSS and JS works for me:

```
.disable-hover {
  pointer-events: none;
}
```
and

```
/* Add workaround for fastclick.js hover issue: https://github.com/ftlabs/fastclick/issues/83 */
var body = document.body;

window.addEventListener('touchstart', function () {
    if (!body.classList.contains('disable-hover')) {
        body.classList.add('disable-hover');
    }

}, false);

window.addEventListener('touchend', function () {
    if (body.classList.contains('disable-hover')) {
        body.classList.remove('disable-hover');
    }

}, false);
```
