### ISSUE TITLE
Chrome on Android with user-scalable="no" doesn't need FastClick

### ISSUE THREAD

**Issue by mattcg** [ftlabs/fastclick#89]

**Comment by ipluser** [comment]
Hi, I meet a problem, e.g.

```html
<div class="wrapper">
    <div class="content">
        <div class="item">
            ...
            <a class="share-link">...</div>
        </div>
        <div class="item">
            ...
            <a class="share-link">...</div>
        </div>
        <div class="item">
            ...
            <a class="share-link">...</div>
        </div>
   </div>
</div>
```

 - come true scroller with `touchstart`, `touchmove`, `touchend` and `transform`.
 - set `.content` element scroll animation
 - add click event for `.share-link` element

 At mobile chrome 33, it will causes twice click event when I click the `.share-link` element.

 I want to know why add below code:

 ```js
 if (metaViewport.content.indexOf('user-scalable=no') !== -1) {
     return true;
 }
 ```

  It doesn't causes twice click event when I remove this code.
